### ISSUE TITLE
Contao 4.4 - no hyphenation

### ISSUE THREAD

**Issue by reluem** [heimrichhannot/contao-hyphenator#1] opened 2017-11-30 09:31 UTC
In Contao 4.4, hyphenation is unfortunately not working for me. No soft hyphens are inserted as happened in Contao 3.5.

The CSS file is also not symlinked to the assets folder (404 on de/system/modules/hyphenator/assets/css/hyphenator.min.css).

Have you tried the hyphenator with Contao 4.4.8?

**Comment by reluem** [comment] 2017-12-02 10:29
additionally, hyphenator breaks the {{ua:agent}} when using [contao-bootstrap/layout](https://github.com/contao-bootstrap/layout).

see here: https://github.com/contao-bootstrap/layout/issues/6

**Comment by fatcrobat** [comment] 2017-12-04 11:45
Hyphenation is currently well supported by common browsers: https://caniuse.com/#feat=css-hyphens. We did not use the package in contao 4 environment yet, and we evaluate the further maintenance of this package due to better browser support.

**Comment by operatorone** [comment] 2018-01-23 09:45
Same problem here. Error message: domain.net/:20 GET https://domain.net/system/modules/hyphenator/assets/css/hyphenator.min.css net::ERR_ABORTED

Also got an output in the frontend using an empty page layout:
 `" itemscope itemtype="http://schema.org/WebPage">`

Which is caused by the inserttag` {{ua::class}}` in the fe_page.html5

**Comment by fatcrobat** [comment] 2018-02-07 15:47
Fixed, sorry for the delay, but sadly chrome has obliged us with to stick with the server side hyphenation.

**Comment by fatcrobat** [comment] 2018-02-07 16:18
Only working in dev mode, this is related to <esi> tags used in contao 4.

**Comment by fatcrobat** [comment] 2018-02-07 17:28
Fixed in 1.1.1.

**Closed as completed by fatcrobat** 2018-02-07 17:28 UTC
Labels: bug
